plugins {
    id 'com.android.library'
    id 'com.google.protobuf'
}

apply from: project(':common').projectDir.absolutePath + '/variables.gradle'

android {
    namespace = 'com.abrenoch.hyperiongrabber.common'
    compileSdk = 36
    buildToolsVersion = '36.0.0'

    defaultConfig {
        minSdk = 21
        testInstrumentationRunner = 'android.support.test.runner.AndroidJUnitRunner'
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "com.android.support:support-v4:$android_support_version"
    implementation "com.android.support:support-vector-drawable:$android_support_version"
    implementation "com.android.support:appcompat-v7:$android_support_version"
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.google.protobuf:protobuf-javalite:4.35.1'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:4.35.1'
    }
    generateProtoTasks {
        all().configureEach { task ->
            task.builtins {
                java {
                    option 'lite'
                }
            }
        }
    }
}
